name: StockBot
on:
  schedule:
    - cron: '0 8 * * *' # 北京时间下午4点跑
  workflow_dispatch:

permissions:
  issues: write

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # 升级到 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install akshare pandas

      - name: Run Scan
        run: |
          python main.py > result.txt
          cat result.txt

      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Daily Stock Report - ${{ github.run_id }}
          content-filepath: ./result.txt
